[Service]
BootTimeout = 30000
CheckInterval = '10s'
Host = 'localhost'  # set this to the IP address of the system host
ServerBindAddr = ''  # blank value defaults to Service.Host value
Port = 49750  #modified to be different than existing device services
Protocol = 'http'
StartupMsg = 'CoAP device started'
Timeout = 20000
ConnectRetries = 20
Labels = []
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = 'edgex-core-consul'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.Data]
  Protocol = 'http'
  Host = 'edgex-core-data'
  Port = 48080

  [Clients.Metadata]
  Protocol = 'http'
  Host = 'edgex-core-metadata'
  Port = 48081

[Device]
  DataTransform = true
  InitCmd = ''
  InitCmdArgs = ''
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ''
  RemoveCmdArgs = ''
  ProfilesDir = './res'
  UpdateLastConnected = false
  [Device.Discovery]
    Enabled = false
    Interval = '30s'

[Driver]
  SecurityMode = 'NoSec'

[Logging]
  LogLevel = 'INFO'

# Pre-define Devices
[[DeviceList]]
  Name = 'd1'
  Profile = 'Coap-Device'
  Description = 'Coap Data Generator Device'
  Labels = [ "coap", "rest" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
